In [6]:
#### 1. Import the numpy package under the name `np` (★☆☆)
#hint: import … as`
import numpy as np

In [7]:
#### 2. Create a null vector of size 10 (★☆☆)
#`hint: np.zeros`
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
#`hint: array[4]`
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [18]:
#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
#`hint: arange`
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [20]:
#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
#`hint: reshape`
a = np.arange(0,9)
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
#`hint: np.nonzero`
a = np.array([1,2,0,0,4,0])
a = np.nonzero(a)
a

(array([0, 1, 4], dtype=int64),)

In [27]:
#### 7. Create a 3x3 identity matrix (★☆☆)
#`hint: np.eye`
a = np.eye(3,3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
#### 8. Create a 3x3x3 array with random values (★☆☆)
#`hint: np.random.random`
a = np.random.random((3,3,3))
a

array([[[0.45636641, 0.46499116, 0.85907082],
        [0.30400316, 0.0128191 , 0.7124914 ],
        [0.84153154, 0.55321139, 0.15146736]],

       [[0.31112805, 0.30230691, 0.09467163],
        [0.9375317 , 0.55884426, 0.5168489 ],
        [0.14797106, 0.67334635, 0.88535495]],

       [[0.84594931, 0.04263012, 0.98947407],
        [0.20060368, 0.29297393, 0.2412709 ],
        [0.38929767, 0.865778  , 0.67936995]]])

In [38]:
#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
#`hint: min, max`
a = np.random.random((10,10))
print(a)
print(a.min())
print(a.max())

[[0.88408992 0.06211278 0.20703413 0.47174651 0.62734316 0.59206014
  0.69536315 0.14770109 0.66268589 0.74727573]
 [0.35248929 0.21962555 0.83203369 0.81722392 0.12256609 0.95238247
  0.98900229 0.9758577  0.23002201 0.57499161]
 [0.06682284 0.18738809 0.54795771 0.42362073 0.54139115 0.27024193
  0.21648149 0.48221482 0.22315999 0.01458261]
 [0.0632903  0.91232911 0.2080445  0.4073774  0.90980821 0.61718956
  0.76015057 0.03226944 0.12976337 0.37741377]
 [0.61214761 0.26962444 0.73779806 0.49042466 0.53117246 0.78560885
  0.98882629 0.18935255 0.2419456  0.49435163]
 [0.39070198 0.31616219 0.74262166 0.66645105 0.2062869  0.06850633
  0.93236585 0.93129447 0.54845032 0.28109264]
 [0.63089197 0.56341182 0.23910327 0.72581997 0.86387199 0.63371477
  0.14441538 0.10831319 0.39167132 0.0444215 ]
 [0.56867156 0.55530988 0.25758168 0.8602247  0.14581727 0.67602477
  0.33437341 0.91265944 0.48568611 0.24495757]
 [0.3054652  0.69622612 0.31890086 0.11336078 0.61465599 0.24469916
  0.06022423

In [40]:
#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
#`hint: mean`
a = np.random.random((30))
print(a)
print(a.mean())

[0.53958635 0.43527029 0.91020028 0.74982902 0.14909046 0.34307989
 0.50015666 0.72139129 0.00931049 0.54869769 0.37372213 0.99817614
 0.56429456 0.95665467 0.57512228 0.41077925 0.72355158 0.55770487
 0.23948577 0.99937904 0.38171292 0.6679964  0.44863525 0.2848031
 0.13989189 0.23025114 0.10132097 0.76828982 0.3347666  0.72782183]
0.513032422088474


In [53]:
#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
#`hint: np.diag`
a = np.diag((1,2,3,4),k=-1)
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [62]:
#### 12. Normalize a 5x5 random matrix (★☆☆)
#`hint: (x -mean)/std`
a = np.random.randint(10, size=(5,5))
print(a)
a = (a - a.min())/ (a.max() - a.min())
a


[[6 3 4 8 5]
 [2 9 6 3 8]
 [8 5 6 2 0]
 [8 4 1 0 5]
 [7 6 4 0 4]]


array([[0.66666667, 0.33333333, 0.44444444, 0.88888889, 0.55555556],
       [0.22222222, 1.        , 0.66666667, 0.33333333, 0.88888889],
       [0.88888889, 0.55555556, 0.66666667, 0.22222222, 0.        ],
       [0.88888889, 0.44444444, 0.11111111, 0.        , 0.55555556],
       [0.77777778, 0.66666667, 0.44444444, 0.        , 0.44444444]])

In [64]:
#### 12. Normalize a 5x5 random matrix (★☆☆)
#`hint: (x -mean)/std`
a = np.random.randint(10, size=(5,5))
print(a)
a = (a - a.mean())/ (a - a.std())
a

[[7 6 2 4 0]
 [7 9 4 4 5]
 [2 0 4 8 9]
 [7 3 1 0 5]
 [0 0 7 1 1]]


array([[  0.78784263,   0.71738076,   1.86037733,   0.15826646,
          1.28469055],
       [  0.78784263,   0.85843288,   0.15826646,   0.15826646,
          0.57684084],
       [  1.86037733,   1.28469055,   0.15826646,   0.83018135,
          0.85843288],
       [  0.78784263, -76.68901225,   1.42781969,   1.28469055,
          0.57684084],
       [  1.28469055,   1.28469055,   0.78784263,   1.42781969,
          1.42781969]])

In [69]:
#### 13. How to find common values between two arrays? (★☆☆)
#`hint: np.intersect1d`
a = np.array([1,2,3,4,5,6])
b = np.array([2,2,2,5,5,5])
print(a)
print(b)
c = np.intersect1d(a,b)
c

[1 2 3 4 5 6]
[2 2 2 5 5 5]


array([2, 5])

In [78]:
#### 14. Create a random vector of size 10 and sort it (★★☆)
#`hint: sort`
a = np.random.randint(10,size=10)
print(a)
a.sort()
a


[9 2 9 1 1 8 8 6 4 8]


array([1, 1, 2, 4, 6, 8, 8, 8, 9, 9])

In [99]:
#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
#`hint: argmax`
a = np.random.randint(100,size=10)
print(a)
print(np.argmax(a))
x = np.argmax(a)
a[x] = 0
print(a)
#a.max()

[64 28 65 64 41  9 56 84 55 14]
7
[64 28 65 64 41  9 56  0 55 14]


In [110]:
#### 16. Subtract the mean of each row of a matrix (★★☆)
#`hint: mean(axis=,keepdims=)`
a = np.random.randint(10,size=(4,4))
print(a)
print(a.mean(axis=1,keepdims=1))
x = a.mean(axis=1,keepdims=1)
c = a - x
print(c)

[[3 4 9 6]
 [7 6 0 1]
 [4 8 0 0]
 [9 4 1 5]]
[[5.5 ]
 [3.5 ]
 [3.  ]
 [4.75]]
[[-2.5  -1.5   3.5   0.5 ]
 [ 3.5   2.5  -3.5  -2.5 ]
 [ 1.    5.   -3.   -3.  ]
 [ 4.25 -0.75 -3.75  0.25]]


In [113]:
#### 17. How to get the n largest values of an array (★★★)
#`Z = np.arange(10000)
#np.random.shuffle(Z)
#n = 5
#hint: np.argsort | np.argpartition`
    
Z = np.arange(10000)
np.random.shuffle(Z)


[ 112 6966 4138 ... 8168 3133 8703]


In [ ]:
#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
`hint: np.where`